# Generated by Django 6.0.2 on 2026-03-06 16:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(64)], verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, verbose_name='Gender')),
                ('region', models.CharField(choices=[('southeast', 'Southeast'), ('southwest', 'Southwest'), ('northwest', 'Northwest'), ('northeast', 'Northeast')], default='southeast', max_length=15, verbose_name='Region')),
                ('smoker', models.BooleanField(default=False, verbose_name='Smoker')),
                ('children', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Number of children')),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('Unemployed', 'Unemployed'), ('White collar', 'White collar'), ('Blue collar', 'Blue collar')], default='Unemployed', max_length=20, verbose_name='Occupation')),
                ('bmi', models.FloatField(default=0, verbose_name='BMI')),
                ('medical_history', models.CharField(choices=[('no', 'No'), ('Heart disease', 'Heart disease'), ('High blood pressure', 'High blood pressure'), ('Diabetes', 'Diabetes')], default='no', max_length=20, verbose_name='Medical History')),
                ('family_medical_history', models.CharField(choices=[('no', 'No'), ('Heart disease', 'Heart disease'), ('High blood pressure', 'High blood pressure'), ('Diabetes', 'Diabetes')], default='no', max_length=20, verbose_name='Family Medical History')),
                ('exercise_frequency', models.CharField(choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Rarely', 'Rarely'), ('Frequently', 'Frequently')], default='No', max_length=12, verbose_name='Exercise Frequency')),
                ('insurance_profile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=500)),
                ('coverage_limit', models.FloatField(default=0)),
                ('premium', models.FloatField(default=0)),
                ('deductibles', models.FloatField(default=0)),
                ('waiting_period', models.FloatField(default=0)),
                ('policy_period', models.FloatField(default=0)),
                ('network_options', models.CharField(choices=[('Access to 50+ hospitals, clinics, and healthcare providers', 'Access to 50+ hospitals, clinics, and healthcare providers'), ('Access to 100+ hospitals, clinics, and healthcare providers', 'Access to 100+ hospitals, clinics, and healthcare providers'), ('Access to 200+ hospitals, clinics, and healthcare providers', 'Access to 200+ hospitals, clinics, and healthcare providers')], max_length=1000)),
                ('coverage_options', models.ManyToManyField(to='insurance.coverageoption')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('predicted_amt', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=15)),
                ('reviewed', models.BooleanField(default=False)),
                ('insurance_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile_proposal', to='insurance.insuranceprofile')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_proposals', to='insurance.package')),
            ],
        ),
    ]
