# Generated by Django 6.0.2 on 2026-02-17 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=18, null=True, verbose_name='Age')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6, verbose_name='Sex')),
                ('region', models.CharField(choices=[('southeast', 'Southeast'), ('southwest', 'Southwest'), ('northwest', 'Northwest'), ('northeast', 'Northeast')], default='southeast', max_length=15, verbose_name='Region')),
                ('smoker', models.BooleanField(default=False, verbose_name='Smoker')),
                ('children', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of children')),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('White collar', 'White collar'), ('Blue collar', 'Blue collar'), ('Unemployed', 'Unemployed')], default='Unemployed', max_length=20, verbose_name='Occupation')),
                ('bmi', models.FloatField(default=0, verbose_name='BMI')),
                ('medical_history', models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('High Blood Pressure', 'High Blood Pressure'), ('No', 'No'), ('Diabetes', 'Diabetes')], default='No', max_length=20, verbose_name='Medical History')),
                ('family_medical_history', models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('High Blood Pressure', 'High Blood Pressure'), ('No', 'No'), ('Diabetes', 'Diabetes')], default='No', max_length=20, verbose_name='Family Medical History')),
                ('insurance_profile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=500)),
                ('coverage_limit', models.FloatField(default=0)),
                ('premium', models.FloatField(default=0)),
                ('deductibles', models.FloatField(default=0)),
                ('waiting_period', models.FloatField(default=0)),
                ('policy_period', models.FloatField(default=0)),
                ('network_options', models.CharField(choices=[('Access to 50+ hospitals, clinics, and healthcare providers', 'Access to 50+ hospitals, clinics, and healthcare providers'), ('Access to 100+ hospitals, clinics, and healthcare providers', 'Access to 100+ hospitals, clinics, and healthcare providers'), ('Access to 200+ hospitals, clinics, and healthcare providers', 'Access to 200+ hospitals, clinics, and healthcare providers')], max_length=1000)),
                ('coverage_options', models.ManyToManyField(blank=True, null=True, to='insurance.coverageoption')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('predicted_amt', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=15, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=87)),
                ('insurance_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile_userx', to='insurance.insuranceprofile')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_package', to='insurance.package')),
                ('userx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_userx', to='user.userx')),
            ],
        ),
    ]
