# Generated by Django 4.2.7 on 2024-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='coverage_options',
        ),
        migrations.AddField(
            model_name='package',
            name='coverage_options',
            field=models.ManyToManyField(blank=True, null=True, to='insurance.coverageoption'),
        ),
    ]
