# Generated by Django 6.0.2 on 2026-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprofile',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='insuranceprofile',
            name='children',
            field=models.IntegerField(default=0, verbose_name='Number of children'),
        ),
    ]
