# Generated by Django 6.0.2 on 2026-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='coverage_options',
            field=models.ManyToManyField(to='insurance.coverageoption'),
        ),
    ]
