# Generated by Django 4.2.7 on 2024-01-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('insurance', '0002_proposal_accepted_proposal_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='proposal',
            name='userx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_userx', to='user.userx'),
        ),
    ]
