# Generated by Django 4.2.7 on 2024-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_coverageoption_remove_package_coverage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='confidence',
            field=models.FloatField(default=87),
        ),
    ]
