# Generated by Django 6.0.2 on 2026-03-05 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_package_coverage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprofile',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(64)], verbose_name='Age'),
        ),
    ]
