# Generated by Django 6.0.2 on 2026-03-05 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_insuranceprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprofile',
            name='children',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Number of children'),
        ),
    ]
