# Generated by Django 4.2.7 on 2024-01-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userx_insurance_profile'),
        ('insurance', '0003_remove_proposal_user_proposal_userx'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='insurance_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile_userx', to='user.userx'),
        ),
    ]
