# Generated by Django 4.2.7 on 2024-01-01 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0004_proposal_insurance_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('region', models.CharField(choices=[('southeast', 'Southeast'), ('southwest', 'Southwest'), ('northwest', 'Northwest'), ('northeast', 'Northeast')], default='southeast', max_length=15)),
                ('smoker', models.BooleanField(default=True)),
                ('children', models.IntegerField(blank=True, default=0, null=True)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('White collar', 'White collar'), ('Blue collar', 'Blue collar'), ('Unemployed', 'Unemployed')], default='Unemployed', max_length=20)),
                ('bmi', models.FloatField(default=0)),
                ('medical_history', models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('High Blood Pressure', 'High Blood Pressure'), ('No', 'No'), ('diabetes', 'Diabetes')], default='No', max_length=20)),
                ('family_medical_history', models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('High Blood Pressure', 'High Blood Pressure'), ('No', 'No'), ('diabetes', 'Diabetes')], default='No', max_length=20)),
                ('insurance_profile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='insurance_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile_userx', to='insurance.insuranceprofile'),
        ),
    ]
