# Generated by Django 6.0.2 on 2026-03-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insuranceprofile_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprofile',
            name='family_medical_history',
            field=models.CharField(choices=[('no', 'No'), ('Heart disease', 'Heart disease'), ('High blood pressure', 'High blood pressure'), ('Diabetes', 'Diabetes')], default='no', max_length=20, verbose_name='Family Medical History'),
        ),
        migrations.AlterField(
            model_name='insuranceprofile',
            name='medical_history',
            field=models.CharField(choices=[('no', 'No'), ('Heart disease', 'Heart disease'), ('High blood pressure', 'High blood pressure'), ('Diabetes', 'Diabetes')], default='no', max_length=20, verbose_name='Medical History'),
        ),
    ]
