# Generated by Django 4.2.7 on 2024-01-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_insuranceprofile_alter_proposal_insurance_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='accepted',
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], max_length=15, null=True),
        ),
    ]
