# Generated by Django 6.0.2 on 2026-03-06 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_insuranceprofile_family_medical_history_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='insurance_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_profile_proposal', to='insurance.insuranceprofile'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_proposals', to='insurance.package'),
        ),
    ]
