# Generated by Django 6.0.2 on 2026-02-17 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, default=18, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('region', models.CharField(choices=[('southeast', 'Southeast'), ('southwest', 'Southwest'), ('northwest', 'Northwest'), ('northeast', 'Northeast')], default='southeast', max_length=15)),
                ('smoker', models.BooleanField(default=True)),
                ('children', models.IntegerField(blank=True, default=0, null=True)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('White collar', 'White collar'), ('Blue collar', 'Blue collar'), ('Unemployed', 'Unemployed')], default='Unemployed', max_length=20)),
                ('bmi', models.FloatField(default=0)),
                ('medical_history', models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('High Blood Pressure', 'High Blood Pressure'), ('No', 'No'), ('diabetes', 'Diabetes')], default='No', max_length=20)),
                ('family_medical_history', models.CharField(choices=[('Heart Disease', 'Heart Disease'), ('High Blood Pressure', 'High Blood Pressure'), ('No', 'No'), ('diabetes', 'Diabetes')], default='No', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userx_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
