# Generated by Django 6.0.2 on 2026-03-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserX',
        ),
    ]
