# Generated by Django 4.2.7 on 2024-01-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userx_insurance_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userx',
            name='insurance_profile',
        ),
    ]
